### ISSUE TITLE
Whitepaper to Blockchain Ownership/IP

### ISSUE THREAD

**Issue by bobbybeckner** [Vulpos/website#12]

**Comment by fadiadmo** [comment]
### SHA256

512d35a9eeb355cd1dc68916631291e3f32ccd27e082d51733fdd6231feab310

### BTC TX 

https://live.blockcypher.com/btc/tx/ae4a76402b8ff1c20dcd62a3635f9cc97b07741bb0e246c006e166afa2220c5c/

### HEX

444f4350524f4f46512d35a9eeb355cd1dc68916631291e3f32ccd27e082d51733fdd6231feab310

[Whitepaper 2 May.pdf](https://github.com/Vulpos/website/files/2029506/Whitepaper.2.May.pdf)
